[server]
headless = true
port = 8501
enableXsrfProtection = true
address = "0.0.0.0"

[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#e0e7ff"
textColor = "#0f172a"



